#!/bin/bash
# This script runs automatically inside the Docker container.

echo "INFO: Preparing project..."
# Our API will place the teacher's project in `/autograder/tests`
# and the student's code in `/autograder/source/Solution.java`.
cp -r /autograder/tests/* .
STUDENT_SRC_PATH=$(find . -path '*/src/main/java' -type d)
cp /autograder/source/Solution.java $STUDENT_SRC_PATH/

echo "INFO: Compiling and running tests..."
# Run the standard Maven test command.
mvn test > /autograder/raw_output.log 2>&1

echo "INFO: Translating results..."
# Find the XML report generated by JUnit.
LATEST_REPORT=$(find target/surefire-reports -name '*.xml' -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d' ')

# Run our Python script to convert the XML into our standard `results.json`.
python3 translate_results.py $LATEST_REPORT /autograder/results/results.json

echo "INFO: Grading complete."